### PR TITLE
added index.html to MATLAB capstone bioeng lesson

### PR DESCRIPTION
**Pull request by IsaKiko**
added index.html

### CODE REVIEW

**Comment by wking** [comment]
On Mon, Apr 20, 2015 at 04:05:40PM -0700, Isabell Kiral-Kornek wrote:

> - added index.html

This looks pretty good to me.

Minor style suggestions to the index.md source:
- “software carpentry” → “Software Carpentry”.
- “loading .mat-files” → “loading `.mat`-files”.
- “in MATLAB software carpentry lesson” → “in a MATLAB Software
  Carpentry lesson”.

You might also want to rename the topic to 01-capstone.md or some such
to get the recommended numeric prefix (dd-slug.md in the docs [1](https://github.com/swcarpentry/lesson-example/blob/3fc6ebf566a73af1803eb201b0b87d25ee7d9284/LAYOUT.md#pages)).

**Comment by IsaKiko** [comment]
Thanks for having a look at this! 
Feedback incorporated.

**Comment by wking** [comment]
On Mon, Apr 20, 2015 at 04:23:50PM -0700, Isabell Kiral-Kornek wrote:

> Thanks for having a look at this! 

No problem :).

And I was suggesting backticks around .mat (so “`.mat`”, not “.'mat'”)
to get “<code>.mat</code>-files” in the Markdown-expanded HTML.

**Comment by IsaKiko** [comment]
Ah, thank you! Fixed.

**Comment by wking** [comment]
On Mon, Apr 20, 2015 at 04:58:31PM -0700, Isabell Kiral-Kornek wrote:

> Ah, thank you! Fixed. 

Looks good to me, thanks :).

**Comment by jiffyclub** [comment]
Looks good to me. @IsaKiko, I'll let you resolve this and #4. Since this is a matlab lesson I've added this repo to the @swcarpentry/matlab-maintainers team so you and @ashwinsrnth can merge PRs here.

**Pull request merged**
